import Mock from 'mockjs'

let List=[]
export default{
    getStatisticalData:()=>{
        for(let i=0;i<7;i++){
            List.push(//将数据push到List中，最后有七段数据，每段数据一个对象
                Mock.mock({//利用mock的random模板生成规则，生成模拟数据
                    苹果:Mock.Random.float(100,8000,0,0),
                    vivo:Mock.Random.float(100,8000,0,0),
                    oppo:Mock.Random.float(100,8000,0,0),
                    魅族:Mock.Random.float(100,8000,0,0),
                    三星:Mock.Random.float(100,8000,0,0),
                    小米:Mock.Random.float(100,8000,0,0)
                })
            )
        }
        
            var list=[];
            for(let i=0;i<7;i++)
            {
                list.push(Mock.Random.date())
            }
            
        
        return{
            code:20000,//状态码20000 表示正常数据
            data:{
                videoData:[//饼图
                    {
                        name:'小米',
                        value:2999
                    },
                    {
                        name:'苹果',
                        value:5999
                    },
                    {
                        name:'vivo',
                        value:1500
                    },
                    {
                        name:'oppo',
                        value:1999
                    },
                    {
                        name:'魅族',
                        value:2500
                    },
                    {
                        name:'三星',
                        value:4500
                    },
                ],

                userData:[//柱状图
                    {
                        data:'周一',
                        new:5,
                        active:200
                    },
                    {
                        data:'周二',
                        new:10,
                        active:500
                    },
                    {
                        data:'周三',
                        new:12,
                        active:550
                    },
                    {
                        data:'周四',
                        new:60,
                        active:800
                    },
                    {
                        data:'周五',
                        new:65,
                        active:850
                    },
                    {
                        data:'周六',
                        new:70,
                        active:900
                    },
                    {
                        data:'周七',
                        new:75,
                        active:950
                    }
                ],
                orderData:{//折线图
                    date:list,
                    data:List
                },
                tableData:[
                    {
                        name:'oppo',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'vivo',
                        todayBuy:300,
                        monthBuy:2200,
                        totalBuy:24000
                    },
                    {
                        name:'苹果',
                        todayBuy:800,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'三星',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'小米',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'魅族',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    }
                ]
            }
        }
    }
}